%YAML 1.0


#Vehicle
Vehicle.width: 1.6
Vehicle.length: 2.6
Vehicle.wheelbase: 1.6
Vehicle.length_front: 0.8
Vehicle.length_rear: 0.8 #length_rear + length_front = wheelbase
Vehicle.cm_lidar_dist: 1.0
#Road
Road.lanewidth: 3.0

#Camera

#Map
Map.width: 200
Map.height: 200
#TODO Change this
Map.resolution: 0.03  #m/pix

Map.obstacle.paddingx: 1 #for occupancy_map_raw rect arount occupied points
Map.obstacle.paddingy: 1 #for occupancy_map_raw rect arount occupied points
Map.obstacle.safex: 16 #for occupancy_map ellipse arount occupied points
Map.obstacle.safey: 32 #for occupancy_map ellipse arount occupied points
Map.obstacle.min_range: 0.4
#Map.obstacle.max_range: 4.0
Map.obstacle.max_range: 1.5
Map.obstacle.min_theta: -10
Map.obstacle.max_theta: 190


#Path Plan
Path.headings: 12
